name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: dfgarciac1/dfgarciac1-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.a57c7405-0831-4210-9e09-29f750fc0373 }}
